version: '3.8'
services:
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass adminpass
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
